from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

from core import capability_registry as reg


class SeedAndPersistenceTests(unittest.TestCase):
    def test_seed_contains_two_verified_capabilities(self):
        seed = reg.seed_registry()
        self.assertEqual(seed["active"],
                         {"arm": "right_arm", "hand_id": "yinshi-right-1"})
        directions = {cap["task"]["direction"]
                      for cap in seed["capabilities"]}
        self.assertEqual(directions, {"rtl", "ltr"})
        for cap in seed["capabilities"]:
            self.assertEqual(cap["method"], "flick")
            self.assertTrue(cap["enabled"])
            # 参数块补齐为现有代码默认值
            self.assertEqual(cap["method_params"], {
                "sidestep_cm": 10.0, "push_force_n": 15.0,
                "push_hold_s": 1.5, "down_deg": 15.0,
            })

    def test_seed_sites_reproduce_site_supported_kinds(self):
        seed = reg.seed_registry()
        rtl = next(c for c in seed["capabilities"]
                   if c["task"]["direction"] == "rtl")
        ltr = next(c for c in seed["capabilities"]
                   if c["task"]["direction"] == "ltr")
        self.assertEqual(rtl["task"]["sites"], ["lab", "factory"])
        self.assertEqual(ltr["task"]["sites"], ["factory"])

    def test_ensure_registry_writes_seed_on_first_run(self):
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "capability_registry.json"
            registry = reg.ensure_registry(path, root=Path(temporary))
            self.assertTrue(path.is_file())
            on_disk = json.loads(path.read_text(encoding="utf-8"))
            self.assertEqual(on_disk["schema_version"], 1)
            self.assertEqual(len(on_disk["capabilities"]), 2)
            # 再次加载与首次一致
            self.assertEqual(reg.load_registry(path), registry)

    def test_save_and_reload_roundtrip(self):
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "capability_registry.json"
            seed = reg.seed_registry()
            seed["hands"].append({
                "id": "qiangnao-left-1", "name": "强脑-左-1",
                "design_side": "left", "tool_out_mm": 12.0, "notes": "",
            })
            saved = reg.save_registry(seed, path)
            self.assertEqual(reg.load_registry(path), saved)
            self.assertEqual(len(saved["hands"]), 2)


class ValidationTests(unittest.TestCase):
    def _seed(self):
        return reg.seed_registry()

    def test_rejects_duplicate_hand_name(self):
        seed = self._seed()
        seed["hands"].append({
            "id": "another", "name": "因时-右-1", "design_side": "right",
        })
        with self.assertRaises(ValueError):
            reg.validate_registry(seed)

    def test_rejects_capability_with_unknown_hand(self):
        seed = self._seed()
        seed["capabilities"][0]["hand_id"] = "no-such-hand"
        with self.assertRaises(ValueError):
            reg.validate_registry(seed)

    def test_rejects_unknown_method_param(self):
        seed = self._seed()
        seed["capabilities"][0]["method_params"] = {"bogus": 1.0}
        with self.assertRaises(ValueError):
            reg.validate_registry(seed)

    def test_rejects_out_of_range_push_hold(self):
        seed = self._seed()
        seed["capabilities"][0]["method_params"] = {"push_hold_s": 9.0}
        with self.assertRaises(ValueError):
            reg.validate_registry(seed)

    def test_rejects_pose_pattern_without_group(self):
        seed = self._seed()
        seed["capabilities"][0]["assets"]["pose_pattern"] = r"^起手式$"
        with self.assertRaises(ValueError):
            reg.validate_registry(seed)

    def test_rejects_active_pointing_to_missing_hand(self):
        seed = self._seed()
        seed["active"] = {"arm": "right_arm", "hand_id": "ghost"}
        with self.assertRaises(ValueError):
            reg.validate_registry(seed)

    def test_twist_method_has_empty_params(self):
        seed = self._seed()
        seed["capabilities"][0]["method"] = "twist"
        seed["capabilities"][0]["method_params"] = {}
        validated = reg.validate_registry(seed)
        self.assertEqual(validated["capabilities"][0]["method_params"], {})

    def test_capability_id_autogenerated_when_missing(self):
        seed = self._seed()
        seed["capabilities"][0]["id"] = ""
        validated = reg.validate_registry(seed)
        self.assertTrue(validated["capabilities"][0]["id"].startswith("cap-"))


class CalibrationTests(unittest.TestCase):
    def test_calib_rel_path_is_combo_unique(self):
        self.assertEqual(
            reg.calib_rel_path("right_arm", "yinshi-right-1"),
            "config/hand_eye/right_arm__yinshi-right-1/handeye3d_result.json",
        )

    def test_import_copies_from_source_path(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            source = root / "external" / "handeye3d_result.json"
            source.parent.mkdir(parents=True)
            source.write_text(json.dumps({
                "T_cam2base": [[1, 0, 0, 0]], "solved_at": "2026-08-01",
                "residual_mm": 2.5, "num_samples": 30,
            }), encoding="utf-8")
            registry = reg.seed_registry()
            calib = registry["calibrations"][0]
            calib["source_path"] = str(source)
            self.assertTrue(reg.try_import_calibration(calib, root))
            archived = root / calib["path"]
            self.assertTrue(archived.is_file())
            info = reg.calibration_info(
                registry, "right_arm", "yinshi-right-1", root)
            self.assertEqual(info["status"], "ready")
            self.assertEqual(info["residual_mm"], 2.5)
            self.assertEqual(info["num_samples"], 30)

    def test_missing_source_reports_pending(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            registry = reg.seed_registry()
            calib = registry["calibrations"][0]
            calib["source_path"] = str(root / "nowhere.json")
            self.assertFalse(reg.try_import_calibration(calib, root))
            info = reg.calibration_info(
                registry, "right_arm", "yinshi-right-1", root)
            self.assertEqual(info["status"], "pending")

    def test_unregistered_combo_reports_missing(self):
        registry = reg.seed_registry()
        info = reg.calibration_info(
            registry, "left_arm", "yinshi-right-1",
            Path(tempfile.gettempdir()) / "no-such-root")
        self.assertEqual(info["status"], "missing")


class QueryTests(unittest.TestCase):
    def test_capability_for_matches_direction_and_site(self):
        registry = reg.seed_registry()
        rtl = reg.capability_for(
            registry, "right_arm", "yinshi-right-1", "rtl", "lab")
        self.assertIsNotNone(rtl)
        self.assertEqual(rtl["task"]["name"], "旋钮右到左")
        # 向右拨（ltr）只在 factory 验证过 → lab 不匹配
        self.assertIsNone(reg.capability_for(
            registry, "right_arm", "yinshi-right-1", "ltr", "lab"))
        self.assertIsNotNone(reg.capability_for(
            registry, "right_arm", "yinshi-right-1", "ltr", "factory"))

    def test_disabled_capability_not_matched(self):
        registry = reg.seed_registry()
        for cap in registry["capabilities"]:
            cap["enabled"] = False
        self.assertIsNone(reg.capability_for(
            registry, "right_arm", "yinshi-right-1", "rtl", "factory"))


if __name__ == "__main__":
    unittest.main()
